import { IAccessToken } from 'src/app/shared/interfaces/access-token';
import { IUserOrProjectAttachment } from 'src/app/shared/interfaces/attachments-details';
import { IProjectDetailsData } from 'src/app/shared/interfaces/project-details';
import { ITechnology } from 'src/app/shared/interfaces/technology';
import { IUserAssignedCvData } from 'src/app/shared/interfaces/user-cv';
import { IUserEducationDetails } from 'src/app/shared/interfaces/user-education';
import { IUserPermissionsRole } from 'src/app/shared/interfaces/user-permissions-role';
import { IUserWorkHistory } from 'src/app/shared/interfaces/user-work-history';
import { IUserWorkType } from 'src/app/shared/interfaces/user-work-type';

export interface IUserDetails {
  id: number;
  email: string;
  password: string;
  name: string;
  surname: string;
  positionDescription: string;
  language: null | string;
  endReason: string;
  avatarUrl: string;
  phone: string;
  city: string;
  salary: number;
  address: string;
  skills: null | string;
  experience: null | string;
  isBanned: boolean;
  banReason: null | string;
  birthday: string;
  cvId: null | number;
  startDate: string;
  endDate: string;
  workTypeId: null | number;
  status: string;
  upwork: null | string;
  github: null | string;
  linkedin: null | string;
  telegramTag: null | string;
  individualEntrepreneurName: null | string;
  individualEntrepreneurAddress: null | string;
  individualEntrepreneurIndividualTaxNumber: null | number;
  individualEntrepreneurBankAccounNumber: null | string;
  individualEntrepreneurBankName: null | string;
  individualEntrepreneurBankCode: null | number;
  individualEntrepreneurBeneficiaryBank: null | string;
  individualEntrepreneurSwiftCode: null | string;
  defaultCoverLetter: null | string;
  createdAt: string;
  updatedAt: string;
  cv: null | IUserAssignedCvData;
  workType: IUserWorkType | null;
  roles: IUserPermissionsRole[];
  token?: IAccessToken;
  leadingInProjects: IProjectDetailsData[];
  participatingInProjects: IProjectDetailsData[];
  attachedAttachments: IUserOrProjectAttachment[];
  publishedAttachments: IUserOrProjectAttachment[];
  techStack: ITechnology[];
  educationInfo: IUserEducationDetails[];
  workHistory: IUserWorkHistory[];
}
